
name: Java CI with Gradle

on:
 - push
 - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v2
       with:
         java-version: '21'
         distribution: 'temurin'
     - uses: gradle/gradle-build-action@v2
       with:
        arguments: build
        build-root-directory: app
          # - name: Publish code coverage
          #   uses: paambaati/codeclimate-action@v3.0.0
          #   env:
          #     CC_TEST_REPORTER_ID: 1276139da08ffe13e33c8d21d12dd393fc1d006abc351ccf1d6b8dbd4003ca6a
          #     JACOCO_SOURCE_PATH: app/src/main/java/
          #   with:
          #     coverageCommand: make report
          #     coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco


 
