
name: Java CI with Gradle

on:
 - push
 - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
     - uses: actions/checkout@v4
     - uses: actions/setup-java@v4
       with:
         java-version: '21'
         distribution: 'temurin'
     - uses: gradle/gradle-build-action@v2
       with: build-root-directory: app
       with:
        gradle-version: 8.5
     - run: make build
     - run: ./gradlew checkstyleMain
     - run: ./gradlew test

 
