name: Java CI with Gradle

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app
      - uses: paambaati/codeclimate-action@v3.2.0
        env:
            CC_TEST_REPORTER_ID: 1276139da08ffe13e33c8d21d12dd393fc1d006abc351ccf1d6b8dbd4003ca6a
            JACOCO_SOURCE_PATH: "${{github.workspace}}app/src/main/java
        with:
             coverageCommand: make  -C app report
             debug: true
             coverageLocations: ${{github.workspace}}/app/build/customJacocoReportDir/test/jacocoTestReport.xml:jacoco
